name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0da4fc9c5cdf5aea5389bb81fd1cd4d126eda64415ed310f883aaa4eb243937"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
