name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a82c65047aff21d46c255e8b3f56bdf4c26fa1f640bc7ddb589375bbd65ed9a2"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
