name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7edbaf9145b25c0675a9c8ddfd002d4c9f0d4691eae896b4baa15a6d61028480"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
